### PR TITLE
Replace the `login` method with `get_token` method

### LINKED ISSUE #29: Use token authentication
enhydris-api-client uses an undecent way to authenticate. Its `.login()` method accepts a username and password and uses them to get a token from the server. It subsequently uses the token to authenticate.

This means that the client application (that is, the application that uses the `enhydris-api-client` library) must know the username and password. This defies the reason for the existence of token authentication. Instead, the user should get the token in another way (e.g. in https://openmeteo.org/api/auth/login/) and supply it to the client application.

So, here's what we're going to do:

1. Rename the `.login()` method to a deprecated `.get_token()`. It should do exactly what it's doing now, but in addition it should return the token.
2. Add a `token` argument to the constructor: `EnhydrisApiClient(base_url, token=None)`.

Normally client applications will know the token and will be supplying it to the constructor, and they will not be using `.get_token()`. The reason for the existence of `.get_token()` is for client applications to be able to automatically change their configuration during a transition period.

### PR DESCRIPTION
**Pull request by eyobofficial**
Closes #29

### CODE REVIEW

**Review by aptiko — CHANGES_REQUESTED** [review]
Thanks! Here are some suggested changes:

1. Fix the documentation (the README.rst).
2. The three test cases `SuccessfulLoginTestCase`, `FailedLoginTestCase` and `LoginWithEmptyUsernameTestCase` might be better to rename. How about `GetTokenTestCase`, `GetTokenFailTestCase` and `GetTokenEmptyUsernameTestCase`?
3. Could you add a test in `SuccessfulLoginTestCase` (aka `GetTokenTestCase`) to test for `get_token()`'s return value? But note that the mocking might be a bit complicated and if you haven't done worked with mocks before maybe it's not a good one to start; let me know in that case.

**Comment by aptiko** [comment]
Additional problem: If you supply a token when creating an instance, it doesn't get used anywhere. It would be a good idea to test that in the end-to-end test (and a unit test). The end-to-end test doesn't also need to test `get_token()`, since it's deprecated.

**Comment by aptiko** [comment]
Hey, did you actually run the end-to-end test? It seems strange to me that it would run with the latest change.

**Comment by eyobofficial** [comment]
> Hey, did you actually run the end-to-end test? It seems strange to me that it would run with the latest change.

The end-to-end tests are failing. I am also trying to find out what is causing the failure and resolve it.

**Review by aptiko — CHANGES_REQUESTED** [review]
Thanks, this is much better.

1. Now would be a good time to read "Git and GitHub" in the wiki (go to wiki.antonischristofides.com and search for "Git and GitHub"). But don't change the branch name or switch to using a fork—these are for next time. We'll go forward with this PR in this case.
2. You removed a large comment and a little code in `EnhydrisApiClient.__init__()`. I presume you found out that the problem I'm explaining in the comment doesn't exist. Which version of `requests` did you try it with? We generally use package versions that are prepackaged with the latest Debian stable, in this case requests 2.21. If you tried it with requests<=2.21, that's fine; if you tried it with requests>2.21, you should also try it with requests 2.21.
3. In any case, this change seems unrelated to the rest of the changes. Technically it doesn't belong in this issue. I'm not against fixing little things without opening an issue ("Git and GitHub" explicitly encourages that, in fact), but they must be in separate commits ("Git and GitHub" also mentions this). So make this change in a separate commit. (In this particular case, I think the easiest way is to undo the change, commit the undoing, and then redo the change, and commit the redoing—I'll squash the commits anyway is such a way that there will be two commits; one with the fixing of this issue and one with the removal of this obsolete thing.) In the commit message, explain why you are making this change, in a way that, if I read that commit message, I wouldn't need to ask the questions I asked in (2) above.
4. In the e2e test, you changed `"Processed"` with `150`. This shouldn't work. You probably have an old version of enhydris; update it with `fetch` or `pull` or something.

**Comment by aptiko** [comment]
5. Also fix the problems Travis found!

**Comment by aptiko** [comment]
Thanks!

There are two remaining problems:

1. If you call `EnhydrisApiClient(base_url)`, without a token, it still sets an "Authorization" header, which is invalid. This is easy to fix, and please also write a unit test for that which is very similar to the other one, except it should use something like `.assert_not_called()`.
2. `.get_token()`, besides returning the token, should also set the "Authorization" header (as the `login()` method used to do).

**Pull request merged**
